### ISSUE TITLE
直接报了这个错

### ISSUE THREAD

**Issue by Faithree** [lin-xin/vue-toast#1]

**Comment by Faithree** [comment]
你好，我本地生产了一下项目，然后把你这个加进去，一开始是路径import错了，然后我手动 改路径，然后下面css就有问题，注释掉就可以
Uncaught Error: Module parse failed: E:\simple\vue-toast-master\lib\toast.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .lx-toast{
|     position: fixed;
|     bottom:100px;
    at eval (eval at <anonymous> (build.js:1355), <anonymous>:1:7)
    at Object.<anonymous> (build.js:1355)
    at __webpack_require__ (build.js:660)
    at fn (build.js:84)
    at eval (eval at <anonymous> (build.js:972), <anonymous>:5:90)
    at Object.<anonymous> (build.js:972)
    at __webpack_require__ (build.js:660)
    at fn (build.js:84)
    at Object.<anonymous> (build.js:1342)
    at __webpack_require__ (build.js:660)

**Comment by lin-xin** [comment]
@Faithree 你引入css的代码给我看看

**Comment by Faithree** [comment]
import '../vue-toast-master/lib/toast.css';
import Toast from'../vue-toast-master/lib/index';
Vue.use(Toast);

//下面是css代码
.lx-toast{
    position: fixed;
    bottom:100px;
    left:50%;
    width:180px;
    height:40px;
    line-height: 40px;
    padding:0 10px;
    margin-left: -100px;
    text-align: center;
    z-index:9999;
    font-size:14px;
    color: #fff;
    border-radius: 5px;
    background: rgba(0,0,0,0.7);
    animation: show-toast .5s;
    -webkit-animation: show-toast .5s;
    overflow: hidden;
    text-overflow:ellipsis;
    white-space:nowrap;
}
.lx-toast.lx-toast-top{
    top:50px;
    bottom:inherit;
}
.lx-toast.lx-toast-center{
    top:50%;
    margin-top: -20px;
    bottom:inherit;
}
@keyframes show-toast
{
    from {
        opacity: 0;
        transform: translateY(-10px);
        -webkit-transform: translateY(-10px);
}
    to {
        opacity: 1;
        transform: translateY(0);
        -webkit-transform: translateY(0);
    }
}

.lx-load-mark{
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 9999;
}
.lx-load-box {
    position: fixed;
    z-index: 3;
    width: 7.6em;
    min-height: 7.6em;
    top: 180px;
    left: 50%;
    margin-left: -3.8em;
    background: rgba(0,0,0,0.7);
    text-align: center;
    border-radius: 5px;
    color: #FFFFFF;
}
.lx-load-content {
    margin-top: 64%;
    font-size: 14px;
}
.lx-loading{
    position: absolute;
    width: 0px;
    left: 50%;
    top: 38%;
}
.loading_leaf{
    position: absolute;
    top: -1px;
    opacity: 0.25;
}
.loading_leaf:before {
    content: " ";
    position: absolute;
    width: 9.14px;
    height: 3.08px;
    background: #d1d1d5;
    box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px;
    border-radius: 1px;
    -webkit-transform-origin: left 50% 0px;
    transform-origin: left 50% 0px;
}
.loading_leaf_0 {
    -webkit-animation: opacity-0 1.25s linear infinite;
    animation: opacity-0 1.25s linear infinite;
}
.loading_leaf_0:before {
    -webkit-transform: rotate(0deg) translate(7.92px, 0px);
    transform: rotate(0deg) translate(7.92px, 0px);
}
.loading_leaf_1 {
    -webkit-animation: opacity-1 1.25s linear infinite;
    animation: opacity-1 1.25s linear infinite;
}
.loading_leaf_1:before {
    -webkit-transform: rotate(30deg) translate(7.92px, 0px);
    transform: rotate(30deg) translate(7.92px, 0px);
}
.loading_leaf_2 {
    -webkit-animation: opacity-2 1.25s linear infinite;
    animation: opacity-2 1.25s linear infinite;
}
.loading_leaf_2:before {
    -webkit-transform: rotate(60deg) translate(7.92px, 0px);
    transform: rotate(60deg) translate(7.92px, 0px);
}
.loading_leaf_3 {
    -webkit-animation: opacity-3 1.25s linear infinite;
    animation: opacity-3 1.25s linear infinite;
}
.loading_leaf_3:before {
    -webkit-transform: rotate(90deg) translate(7.92px, 0px);
    transform: rotate(90deg) translate(7.92px, 0px);
}
.loading_leaf_4 {
    -webkit-animation: opacity-4 1.25s linear infinite;
    animation: opacity-4 1.25s linear infinite;
}
.loading_leaf_4:before {
    -webkit-transform: rotate(120deg) translate(7.92px, 0px);
    transform: rotate(120deg) translate(7.92px, 0px);
}
.loading_leaf_5 {
    -webkit-animation: opacity-5 1.25s linear infinite;
    animation: opacity-5 1.25s linear infinite;
}
.loading_leaf_5:before {
    -webkit-transform: rotate(150deg) translate(7.92px, 0px);
    transform: rotate(150deg) translate(7.92px, 0px);
}
.loading_leaf_6 {
    -webkit-animation: opacity-6 1.25s linear infinite;
    animation: opacity-6 1.25s linear infinite;
}
.loading_leaf_6:before {
    -webkit-transform: rotate(180deg) translate(7.92px, 0px);
    transform: rotate(180deg) translate(7.92px, 0px);
}
.loading_leaf_7 {
    -webkit-animation: opacity-7 1.25s linear infinite;
    animation: opacity-7 1.25s linear infinite;
}
.loading_leaf_7:before {
    -webkit-transform: rotate(210deg) translate(7.92px, 0px);
    transform: rotate(210deg) translate(7.92px, 0px);
}
.loading_leaf_8 {
    -webkit-animation: opacity-8 1.25s linear infinite;
    animation: opacity-8 1.25s linear infinite;
}
.loading_leaf_8:before {
    -webkit-transform: rotate(240deg) translate(7.92px, 0px);
    transform: rotate(240deg) translate(7.92px, 0px);
}
.loading_leaf_9 {
    -webkit-animation: opacity-9 1.25s linear infinite;
    animation: opacity-9 1.25s linear infinite;
}
.loading_leaf_9:before {
    -webkit-transform: rotate(270deg) translate(7.92px, 0px);
    transform: rotate(270deg) translate(7.92px, 0px);
}
.loading_leaf_10 {
    -webkit-animation: opacity-10 1.25s linear infinite;
    animation: opacity-10 1.25s linear infinite;
}
.loading_leaf_10:before {
    -webkit-transform: rotate(300deg) translate(7.92px, 0px);
    transform: rotate(300deg) translate(7.92px, 0px);
}
.loading_leaf_11 {
    -webkit-animation: opacity-11 1.25s linear infinite;
    animation: opacity-11 1.25s linear infinite;
}
.loading_leaf_11:before {
    -webkit-transform: rotate(330deg) translate(7.92px, 0px);
    transform: rotate(330deg) translate(7.92px, 0px);
}
@-webkit-keyframes opacity-0 {
  0% { opacity: 0.25; }
  0.01% { opacity: 0.25; }
  0.02% { opacity: 1; }
  60.01% { opacity: 0.25; }
  100% { opacity: 0.25; }
}
@-webkit-keyframes opacity-1 {
  0% { opacity: 0.25; }
  8.34333% { opacity: 0.25; }
  8.35333% { opacity: 1; }
  68.3433% { opacity: 0.25; }
  100% { opacity: 0.25; }
}
@-webkit-keyframes opacity-2 {
  0% { opacity: 0.25; }
  16.6767% { opacity: 0.25; }
  16.6867% { opacity: 1; }
  76.6767% { opacity: 0.25; }
  100% { opacity: 0.25; }
}
@-webkit-keyframes opacity-3 {
  0% { opacity: 0.25; }
  25.01% { opacity: 0.25; }
  25.02% { opacity: 1; }
  85.01% { opacity: 0.25; }
  100% { opacity: 0.25; }
}
@-webkit-keyframes opacity-4 {
  0% { opacity: 0.25; }
  33.3433% { opacity: 0.25; }
  33.3533% { opacity: 1; }
  93.3433% { opacity: 0.25; }
  100% { opacity: 0.25; }
}
@-webkit-keyframes opacity-5 {
  0% { opacity: 0.270958333333333; }
  41.6767% { opacity: 0.25; }
  41.6867% { opacity: 1; }
  1.67667% { opacity: 0.25; }
  100% { opacity: 0.270958333333333; }
}
@-webkit-keyframes opacity-6 {
  0% { opacity: 0.375125; }
  50.01% { opacity: 0.25; }
  50.02% { opacity: 1; }
  10.01% { opacity: 0.25; }
  100% { opacity: 0.375125; }
}
@-webkit-keyframes opacity-7 {
  0% { opacity: 0.479291666666667; }
  58.3433% { opacity: 0.25; }
  58.3533% { opacity: 1; }
  18.3433% { opacity: 0.25; }
  100% { opacity: 0.479291666666667; }
}
@-webkit-keyframes opacity-8 {
  0% { opacity: 0.583458333333333; }
  66.6767% { opacity: 0.25; }
  66.6867% { opacity: 1; }
  26.6767% { opacity: 0.25; }
  100% { opacity: 0.583458333333333; }
}
@-webkit-keyframes opacity-9 {
  0% { opacity: 0.687625; }
  75.01% { opacity: 0.25; }
  75.02% { opacity: 1; }
  35.01% { opacity: 0.25; }
  100% { opacity: 0.687625; }
}
@-webkit-keyframes opacity-10 {
  0% { opacity: 0.791791666666667; }
  83.3433% { opacity: 0.25; }
  83.3533% { opacity: 1; }
  43.3433% { opacity: 0.25; }
  100% { opacity: 0.791791666666667; }
}
@-webkit-keyframes opacity-11 {
  0% { opacity: 0.895958333333333; }
  91.6767% { opacity: 0.25; }
  91.6867% { opacity: 1; }
  51.6767% { opacity: 0.25; }
  100% { opacity: 0.895958333333333; }
}

**Comment by Faithree** [comment]
因为npm install vue-toast下载的是一个外国人的项目，所以我就手动下载，然后放到跟目录下

**Comment by lin-xin** [comment]
你的项目是用vue-cli生成的吗？

**Comment by Faithree** [comment]
是的

**Comment by lin-xin** [comment]
那应该已经有配置好解析css的loader啊，怎么你报错信息还提示需要引入loader。
你方便的话可以把文件夹发给我我调试一下吗？

**Comment by Faithree** [comment]
你试试直接cli生成一个，你QQ多少？

**Comment by lin-xin** [comment]
2981207131
