### ISSUE TITLE
在 Toast 未关闭之前，再次调用不生效

### ISSUE THREAD

**Issue by raisezhang** [lin-xin/vue-toast#13]
是否可以考虑在展现之前把之前的 Remove 掉，然后 Show 呢？

**Comment by lin-xin** [comment]
之前是怕会有第一个toast还没看清楚就被第二个覆盖掉了，所以才这样子设计

**Comment by CK-Chan** [comment]
@lin-xin 楼主，可以把目前的issue给关掉了，这些open的issue看得难受~

**Comment by BusyHe** [comment]
@lin-xin 如果第一个toast正在显示，要显示第二个toast的时，可以替换掉第一个toast的内容，并把隐藏时间重置。这样感觉会好些，毕竟第一个toast还没看清楚就被第二个覆盖掉了这种场景是用户行为
