### ISSUE TITLE
runtime-only 无法使用 template属性

### ISSUE THREAD

**Issue by shmy** [lin-xin/vue-toast#18]
Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by edgarcheverier** [comment]
The same here

**Comment by Joeyueh** [comment]
the same here++

**Comment by lin-xin** [comment]
Please update to the V2.0.0

**Comment by Joeyueh** [comment]
可以说具体点吗，升级什么到2.0.0，我刚看了release并没有新版本

**Comment by Joeyueh** [comment]
![default](https://user-images.githubusercontent.com/28590596/43509542-892118d6-95a5-11e8-8ad2-f89716338f94.png)
打包的时候出错了

**Comment by lin-xin** [comment]
@Joeyueh 我来看看

**Comment by lin-xin** [comment]
@Joeyueh 好了，已经发了 V2.0.1
