### ISSUE TITLE
无法解析CSS！

### ISSUE THREAD

**Issue by bleedkaga** [lin-xin/vue-toast#2]
我参照说明里的 import 'vue2-toast/lib/vue-toast.css' 方法引入CSS， 结果造成如下报错： 
Module not found: Error: Can't resolve 'vue2-toast/lib/vue-toast.css' in '/Users/bleedkaga/Documents/Vue/vue-basic/src'；

是我引入的姿势不对吗？

**Comment by lin-xin** [comment]
@bleedkaga 你的webpack有配置css-loader吗

**Comment by huyongyong1992** [comment]
import 'vue2-toast/lib/vue-toast.css';  我的这样写页报错,有css-loader

**Comment by lin-xin** [comment]
不好意思，是 import 'vue2-toast/lib/toast.css';
