### ISSUE TITLE
调用this.$toast.top('top')时，小程序报错

### ISSUE THREAD

**Issue by nijunjie** [lin-xin/vue-toast#25]
你好，请问在小程序里引用您的toast，当调用this.$toast.top('top')时就会报错
Please do not register multiple Pages

这是main.js， 然后在index.vue里面调用this.$toast.top('top')时就会报错，请您指教，谢谢。
![image](https://user-images.githubusercontent.com/16549894/49038938-36ef8500-f173-11e8-80ea-6b70cb1c81b2.png)

![image](https://user-images.githubusercontent.com/16549894/49038994-5edee880-f173-11e8-95ed-ab2a39f60849.png)

**Comment by lin-xin** [comment]
没用它在小程序上试过啊

**Comment by nijunjie** [comment]
好的，谢谢
