### ISSUE TITLE
Multiple toasts at a time

### ISSUE THREAD

**Issue by sushant-j** [lin-xin/vue-toast#4]
Is there a way I can get multiple toasts at a time?
Perhaps stacked on top of each other.

Like the [demo here](http://astaroverov.github.io/#!/open-source/vue-toast).

**Comment by lin-xin** [comment]
@sushant-j Sorry,it does not support multiple toast

**Comment by sushant-j** [comment]
That's unfortunate. The use case I have required it. 
Anyways, good and really light-weight module!
Kudos to you :)

**Comment by lin-xin** [comment]
Because it is mainly used in the mobile terminal, and the mobile terminal does not require multiple toast.
