### ISSUE TITLE
按照readme引入项目后报错

### ISSUE THREAD

**Issue by musicyy** [lin-xin/vue-toast#6]
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by lin-xin** [comment]
@musicyy 你好，这个报错是在什么情况下的，开发环境下吗？我这边引入没发现有这个问题，我这边找了一篇 ：http://www.imooc.com/article/17868 看看是否对你有帮助
