### ISSUE TITLE
文字太长会显示省略号，但是我希望是全部显示，有参数可以配置吗？

### ISSUE THREAD

**Issue by wangsuidou** [lin-xin/vue-toast#7]
![qq 20170713153710](https://user-images.githubusercontent.com/13782434/28155383-0d8bd708-67e1-11e7-813e-f30d69ed0c4e.png)

**Comment by lin-xin** [comment]
@wangsuidou 不好意思，目前没有。后续可以加上去。如果你目前用的话，可以通过修改css的方式实现。

**Comment by wangsuidou** [comment]
好的，谢谢。

**Comment by lin-xin** [comment]
@wangsuidou 在v1.3.0版本添加参数配置自动换行和宽度。

**Comment by Jyaane-unused** [comment]
请问换行的参数是什么？

**Comment by lin-xin** [comment]
@Jyaane 文档有，wordWrap传false即可
